In [1]:
import numpy as np
np.random.seed(21)

A=np.random.randint(0,10,size=(5, 5))
print("Matrix: A")
print(A)
U,Sigma,VT=np.linalg.svd(A)
print("Matrix U:")
print(U)
print("Matrix Sigma:")
print(np.diag(Sigma))
print("Matrix V^T:")
print(VT)
recon_A=U@np.diag(Sigma)@ VT
print("Is A equal to the product of U, Sigma, and V^T?")
print(np.allclose(A, recon_A))
rank_2 = U[:, :2] @ np.diag(Sigma[:2]) @ VT[:2, :]
print("Rank 2 approximation of A:")
print(rank_2)
print()
rank_3 = U[:, :3] @ np.diag(Sigma[:3]) @ VT[:3, :]
print("Rank 3 approximation of A:")
print(rank_3)

Matrix: A
[[9 8 4 0 0]
 [8 3 2 1 8]
 [9 6 0 4 6]
 [4 4 7 8 9]
 [5 6 5 2 6]]
Matrix U:
[[-0.39398584 -0.7021273  -0.48356478 -0.02402772 -0.34260791]
 [-0.42889724 -0.00956637  0.58147912  0.59627189 -0.34971062]
 [-0.47288003 -0.18456267  0.48676017 -0.65309483  0.28080738]
 [-0.51046394  0.68636756 -0.33877745 -0.21711529 -0.32621607]
 [-0.42027771  0.04197538 -0.27629969  0.41256588  0.75832222]]
Matrix Sigma:
[[25.96092424  0.          0.          0.          0.        ]
 [ 0.          9.78394034  0.          0.          0.        ]
 [ 0.          0.          6.15721003  0.          0.        ]
 [ 0.          0.          0.          3.69776946  0.        ]
 [ 0.          0.          0.          0.          1.64929967]]
Matrix V^T:
[[-0.59228304 -0.45604619 -0.31232994 -0.27906111 -0.5155556 ]
 [-0.52140481 -0.38387101  0.22350993  0.49336709  0.53610847]
 [ 0.3157247  -0.35997273 -0.73478758 -0.11925842  0.4654054 ]
 [-0.03503723 -0.19337089  0.44336329 -0.79180112  0.37129512]
 [-0