In [12]:
import numpy as np
np.random.seed(62)
P=np.random.randint(0, 10, size=(5, 5))
print("Matrix:P")
print(P)

Matrix:P
[[2 8 1 9 3]
 [5 1 4 5 1]
 [9 8 3 5 1]
 [0 3 5 8 0]
 [1 1 1 9 3]]


In [15]:
def row_echelon_form(matrix):
    m=len(matrix)
    n=len(matrix[0])
    lead=0
    for i in range(m):
        if lead>=n:
            break
        r=i
        while matrix[r,lead]==0:
            r+=1
            if r==m:
                r=i
                lead+=1
                if n==lead:
                    break
        matrix[[r,i]]=matrix[[i,r]]
        if matrix[i,lead]!=0:
            matrix[i]=matrix[i]/matrix[i,lead]
        for r in range(m):
            if r!=i:
                matrix[r] = matrix[r] - matrix[r, lead] * matrix[i]
        lead+=1
    return matrix
row_echelon_P=row_echelon_form(P)
print("\nRow Echelon Form of Matrix P:")
print(row_echelon_P)



Row Echelon Form of Matrix P:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
